import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { sidebar } from './sidebar'

// https://vitepress.dev/reference/site-config
export default withMermaid(
  defineConfig({
    lang: 'zh-CN',
    title: 'AI Infra Handbook',
    description: '面向 AI Infrastructure 工程师的开源中文知识库',

    lastUpdated: true,
    cleanUrls: true,

    markdown: {
      lineNumbers: true,
      config: (md) => {
        // 可在此注册自定义 markdown-it 插件
      },
    },

    themeConfig: {
      // https://vitepress.dev/reference/default-theme-config
      nav: [
        { text: '首页', link: '/' },
        { text: '阅读指南', link: '/guide' },
        { text: '学习路线', link: '/10-roadmap/learning-path' },
        {
          text: '云原生',
          items: [
            { text: '概述', link: '/02-cloud-native/' },
            { text: 'Kubernetes 总览', link: '/02-cloud-native/kubernetes/' },
            { text: 'K8s 1. 背景', link: '/02-cloud-native/kubernetes/01-background' },
            { text: 'K8s 2. 核心思想', link: '/02-cloud-native/kubernetes/02-core-ideas' },
            { text: 'K8s 3. 架构设计', link: '/02-cloud-native/kubernetes/03-architecture' },
            { text: 'K8s 4. Runtime 工作流程', link: '/02-cloud-native/kubernetes/04-runtime-workflow' },
            { text: 'K8s 5. 核心模块', link: '/02-cloud-native/kubernetes/05-core-modules' },
            { text: 'K8s 6. 源码分析', link: '/02-cloud-native/kubernetes/06-source-analysis' },
            { text: 'K8s 7. 工程实践', link: '/02-cloud-native/kubernetes/07-mini-demo' },
            { text: 'K8s 8. 企业生产实践', link: '/02-cloud-native/kubernetes/08-production-practice' },
            { text: 'K8s 9. 最佳实践', link: '/02-cloud-native/kubernetes/09-best-practices' },
            { text: 'K8s 10. 面试题', link: '/02-cloud-native/kubernetes/10-interview-questions' },
            { text: 'K8s 11. 延伸阅读', link: '/02-cloud-native/kubernetes/11-further-reading' },
          ],
        },
        {
          text: '容器运行时',
          items: [
            { text: '容器运行时 总览', link: '/02-cloud-native/container-runtime/' },
            { text: 'CR 1. 背景', link: '/02-cloud-native/container-runtime/01-background' },
            { text: 'CR 2. 核心思想', link: '/02-cloud-native/container-runtime/02-core-ideas' },
            { text: 'CR 3. 架构设计', link: '/02-cloud-native/container-runtime/03-architecture' },
            { text: 'CR 4. Runtime 工作流程', link: '/02-cloud-native/container-runtime/04-runtime-workflow' },
            { text: 'CR 5. 核心模块', link: '/02-cloud-native/container-runtime/05-core-modules' },
            { text: 'CR 6. 源码分析', link: '/02-cloud-native/container-runtime/06-source-analysis' },
            { text: 'CR 7. 工程实践', link: '/02-cloud-native/container-runtime/07-mini-demo' },
            { text: 'CR 8. 企业生产实践', link: '/02-cloud-native/container-runtime/08-production-practice' },
            { text: 'CR 9. 最佳实践', link: '/02-cloud-native/container-runtime/09-best-practices' },
            { text: 'CR 10. 面试题', link: '/02-cloud-native/container-runtime/10-interview-questions' },
            { text: 'CR 11. 延伸阅读', link: '/02-cloud-native/container-runtime/11-further-reading' },
          ],
        },
        {
          text: 'Helm',
          items: [
            { text: 'Helm 总览', link: '/02-cloud-native/helm/' },
            { text: 'Helm 1. 背景', link: '/02-cloud-native/helm/01-background' },
            { text: 'Helm 2. 核心思想', link: '/02-cloud-native/helm/02-core-ideas' },
            { text: 'Helm 3. 架构设计', link: '/02-cloud-native/helm/03-architecture' },
            { text: 'Helm 4. Release 工作流程', link: '/02-cloud-native/helm/04-release-workflow' },
            { text: 'Helm 5. 核心模块', link: '/02-cloud-native/helm/05-core-modules' },
            { text: 'Helm 6. 源码分析', link: '/02-cloud-native/helm/06-source-analysis' },
            { text: 'Helm 7. 工程实践', link: '/02-cloud-native/helm/07-mini-demo' },
            { text: 'Helm 8. 企业生产实践', link: '/02-cloud-native/helm/08-production-practice' },
            { text: 'Helm 9. 最佳实践', link: '/02-cloud-native/helm/09-best-practices' },
            { text: 'Helm 10. 面试题', link: '/02-cloud-native/helm/10-interview-questions' },
            { text: 'Helm 11. 延伸阅读', link: '/02-cloud-native/helm/11-further-reading' },
          ],
        },
        {
          text: 'Operator 模式',
          items: [
            { text: 'Operator 总览', link: '/02-cloud-native/operator/' },
            { text: 'Operator 1. 背景', link: '/02-cloud-native/operator/01-background' },
            { text: 'Operator 2. 核心思想', link: '/02-cloud-native/operator/02-core-ideas' },
            { text: 'Operator 3. 架构设计', link: '/02-cloud-native/operator/03-architecture' },
            { text: 'Operator 4. Reconcile 工作流程', link: '/02-cloud-native/operator/04-reconcile-loop' },
            { text: 'Operator 5. 核心模块', link: '/02-cloud-native/operator/05-core-modules' },
            { text: 'Operator 6. 源码分析', link: '/02-cloud-native/operator/06-source-analysis' },
            { text: 'Operator 7. 工程实践', link: '/02-cloud-native/operator/07-mini-demo' },
            { text: 'Operator 8. 企业生产实践', link: '/02-cloud-native/operator/08-production-practice' },
            { text: 'Operator 9. 最佳实践', link: '/02-cloud-native/operator/09-best-practices' },
            { text: 'Operator 10. 面试题', link: '/02-cloud-native/operator/10-interview-questions' },
            { text: 'Operator 11. 延伸阅读', link: '/02-cloud-native/operator/11-further-reading' },
          ],
        },
        {
          text: 'LLMOps',
          items: [
            { text: 'vLLM', link: '/04-llmops/vllm/' },
            { text: 'SGLang', link: '/04-llmops/sglang/' },
            { text: 'TensorRT-LLM', link: '/04-llmops/tensorrt-llm/' },
            { text: 'Triton Inference Server', link: '/04-llmops/triton/' },
            { text: 'LLM Gateway', link: '/04-llmops/llm-gateway/' },
          ],
        },
        {
          text: 'AI 平台',
          items: [
            { text: '概述', link: '/03-ai-platform/' },
            { text: 'Ray 总览', link: '/03-ai-platform/ray/' },
            { text: 'Ray 1. 背景', link: '/03-ai-platform/ray/01-background' },
            { text: 'Ray 2. 核心思想', link: '/03-ai-platform/ray/02-core-ideas' },
            { text: 'Ray 3. 架构设计', link: '/03-ai-platform/ray/03-architecture' },
            { text: 'Ray 4. 执行模型', link: '/03-ai-platform/ray/04-execution-model' },
            { text: 'Ray 5. 核心模块', link: '/03-ai-platform/ray/05-core-modules' },
            { text: 'Ray 6. 源码分析', link: '/03-ai-platform/ray/06-source-analysis' },
            { text: 'Ray 7. Mini Demo', link: '/03-ai-platform/ray/07-mini-demo' },
            { text: 'Ray 8. 企业生产实践', link: '/03-ai-platform/ray/08-production-practice' },
            { text: 'Ray 9. 最佳实践', link: '/03-ai-platform/ray/09-best-practices' },
            { text: 'Ray 10. 面试题', link: '/03-ai-platform/ray/10-interview-questions' },
            { text: 'Ray 11. 延伸阅读', link: '/03-ai-platform/ray/11-further-reading' },
            { text: 'KServe 总览', link: '/03-ai-platform/kserve/' },
            { text: 'KServe 1. 背景', link: '/03-ai-platform/kserve/01-background' },
            { text: 'KServe 2. 核心思想', link: '/03-ai-platform/kserve/02-core-ideas' },
            { text: 'KServe 3. 架构设计', link: '/03-ai-platform/kserve/03-architecture' },
            { text: 'KServe 4. Runtime 工作流程', link: '/03-ai-platform/kserve/04-runtime-workflow' },
            { text: 'KServe 5. 核心模块', link: '/03-ai-platform/kserve/05-core-modules' },
            { text: 'KServe 6. 源码分析', link: '/03-ai-platform/kserve/06-source-analysis' },
            { text: 'KServe 7. Mini Demo', link: '/03-ai-platform/kserve/07-mini-demo' },
            { text: 'KServe 8. 企业生产实践', link: '/03-ai-platform/kserve/08-production-practice' },
            { text: 'KServe 9. 最佳实践', link: '/03-ai-platform/kserve/09-best-practices' },
            { text: 'KServe 10. 面试题', link: '/03-ai-platform/kserve/10-interview-questions' },
            { text: 'KServe 11. 延伸阅读', link: '/03-ai-platform/kserve/11-further-reading' },
            { text: 'Kubeflow 总览', link: '/03-ai-platform/kubeflow/' },
            { text: 'Kubeflow 1. 背景', link: '/03-ai-platform/kubeflow/01-background' },
            { text: 'Kubeflow 2. 核心思想', link: '/03-ai-platform/kubeflow/02-core-ideas' },
            { text: 'Kubeflow 3. 架构设计', link: '/03-ai-platform/kubeflow/03-architecture' },
            { text: 'Kubeflow 4. Runtime 工作流程', link: '/03-ai-platform/kubeflow/04-runtime-workflow' },
            { text: 'Kubeflow 5. 核心模块', link: '/03-ai-platform/kubeflow/05-core-modules' },
            { text: 'Kubeflow 6. 源码分析', link: '/03-ai-platform/kubeflow/06-source-analysis' },
            { text: 'Kubeflow 7. Mini Demo', link: '/03-ai-platform/kubeflow/07-mini-demo' },
            { text: 'Kubeflow 8. 企业生产实践', link: '/03-ai-platform/kubeflow/08-production-practice' },
            { text: 'Kubeflow 9. 最佳实践', link: '/03-ai-platform/kubeflow/09-best-practices' },
            { text: 'Kubeflow 10. 面试题', link: '/03-ai-platform/kubeflow/10-interview-questions' },
            { text: 'Kubeflow 11. 延伸阅读', link: '/03-ai-platform/kubeflow/11-further-reading' },
            { text: 'MLflow 总览', link: '/03-ai-platform/mlflow/' },
            { text: 'MLflow 1. 背景', link: '/03-ai-platform/mlflow/01-background' },
            { text: 'MLflow 2. 核心思想', link: '/03-ai-platform/mlflow/02-core-ideas' },
            { text: 'MLflow 3. 架构设计', link: '/03-ai-platform/mlflow/03-architecture' },
            { text: 'MLflow 4. Runtime 工作流程', link: '/03-ai-platform/mlflow/04-runtime-workflow' },
            { text: 'MLflow 5. 核心模块', link: '/03-ai-platform/mlflow/05-core-modules' },
            { text: 'MLflow 6. 源码分析', link: '/03-ai-platform/mlflow/06-source-analysis' },
            { text: 'MLflow 7. Mini Demo', link: '/03-ai-platform/mlflow/07-mini-demo' },
            { text: 'MLflow 8. 企业生产实践', link: '/03-ai-platform/mlflow/08-production-practice' },
            { text: 'MLflow 9. 最佳实践', link: '/03-ai-platform/mlflow/09-best-practices' },
            { text: 'MLflow 10. 面试题', link: '/03-ai-platform/mlflow/10-interview-questions' },
            { text: 'MLflow 11. 延伸阅读', link: '/03-ai-platform/mlflow/11-further-reading' },
            { text: 'KubeRay 总览', link: '/03-ai-platform/kuberay/' },
            { text: 'KubeRay 1. 背景', link: '/03-ai-platform/kuberay/01-background' },
            { text: 'KubeRay 2. 核心思想', link: '/03-ai-platform/kuberay/02-core-ideas' },
            { text: 'KubeRay 3. 架构设计', link: '/03-ai-platform/kuberay/03-architecture' },
            { text: 'KubeRay 4. Runtime 工作流程', link: '/03-ai-platform/kuberay/04-runtime-workflow' },
            { text: 'KubeRay 5. 核心模块', link: '/03-ai-platform/kuberay/05-core-modules' },
            { text: 'KubeRay 6. 源码分析', link: '/03-ai-platform/kuberay/06-source-analysis' },
            { text: 'KubeRay 7. Mini Demo', link: '/03-ai-platform/kuberay/07-mini-demo' },
            { text: 'KubeRay 8. 企业生产实践', link: '/03-ai-platform/kuberay/08-production-practice' },
            { text: 'KubeRay 9. 最佳实践', link: '/03-ai-platform/kuberay/09-best-practices' },
            { text: 'KubeRay 10. 面试题', link: '/03-ai-platform/kuberay/10-interview-questions' },
            { text: 'KubeRay 11. 延伸阅读', link: '/03-ai-platform/kuberay/11-further-reading' },
          ],
        },
        {
          text: 'Agent',
          items: [
            { text: 'Agent Runtime', link: '/05-agent/agent-runtime/' },
            { text: 'Memory', link: '/05-agent/memory/' },
            { text: 'Multi-Agent', link: '/05-agent/multi-agent/' },
            { text: 'Reflection', link: '/05-agent/reflection/' },
            { text: 'MCP', link: '/05-agent/mcp/' },
            { text: 'Planning', link: '/05-agent/planning/' },
            { text: 'Tool Use', link: '/05-agent/tool-use/' },
            { text: 'Agent OS', link: '/05-agent/agent-os/' },
          ],
        },
        {
          text: 'RAG',
          items: [
            { text: '概述', link: '/06-rag/' },
            { text: '1. 背景', link: '/06-rag/01-background' },
            { text: '2. 核心概念', link: '/06-rag/02-core-ideas' },
            { text: '3. 架构设计', link: '/06-rag/03-architecture' },
            { text: '4. RAG 流水线', link: '/06-rag/04-rag-pipeline' },
            { text: '5. 核心模块', link: '/06-rag/05-core-modules' },
            { text: '6. 源码与生态分析', link: '/06-rag/06-source-analysis' },
            { text: '7. Mini Demo', link: '/06-rag/07-mini-demo' },
            { text: '8. 企业生产实践', link: '/06-rag/08-production-practice' },
            { text: '9. 最佳实践', link: '/06-rag/09-best-practices' },
          ],
        },
        {
          text: 'AI SRE',
          items: [
            { text: '概述', link: '/07-ai-sre/' },
            { text: '1. 背景', link: '/07-ai-sre/01-background' },
            { text: '2. 核心概念', link: '/07-ai-sre/02-core-ideas' },
            { text: '3. 架构设计', link: '/07-ai-sre/03-architecture' },
            { text: '4. AI SRE 工作流程', link: '/07-ai-sre/04-ai-sre-workflow' },
            { text: '5. 核心模块', link: '/07-ai-sre/05-core-modules' },
            { text: '6. 源码与生态分析', link: '/07-ai-sre/06-source-analysis' },
            { text: '7. Mini Demo', link: '/07-ai-sre/07-mini-demo' },
            { text: '8. 企业生产实践', link: '/07-ai-sre/08-production-practice' },
            { text: '9. 最佳实践', link: '/07-ai-sre/09-best-practices' },
          ],
        },
        {
          text: '安全',
          items: [
            { text: '概述', link: '/08-security/' },
            { text: '1. 背景', link: '/08-security/01-background' },
            { text: '2. 核心思想', link: '/08-security/02-core-ideas' },
            { text: '3. 架构设计', link: '/08-security/03-architecture' },
            { text: '4. AI 安全生命周期', link: '/08-security/04-security-lifecycle' },
            { text: '5. 核心模块', link: '/08-security/05-core-modules' },
            { text: '6. 源码与生态分析', link: '/08-security/06-source-analysis' },
            { text: '7. Mini Demo', link: '/08-security/07-mini-demo' },
            { text: '8. 企业生产实践', link: '/08-security/08-production-practice' },
            { text: '9. 最佳实践', link: '/08-security/09-best-practices' },
          ],
        },
        {
          text: '案例研究',
          items: [
            { text: '概述', link: '/09-case-study/' },
            { text: 'OpenAI 总览', link: '/09-case-study/openai/' },
            { text: 'OpenAI 1. 背景', link: '/09-case-study/openai/01-background' },
            { text: 'OpenAI 2. 核心思想', link: '/09-case-study/openai/02-core-ideas' },
            { text: 'OpenAI 3. 架构设计', link: '/09-case-study/openai/03-architecture' },
            { text: 'OpenAI 4. 训练与推理', link: '/09-case-study/openai/04-training-and-inference' },
            { text: 'OpenAI 5. 核心模块', link: '/09-case-study/openai/05-core-modules' },
            { text: 'OpenAI 6. 源码与生态分析', link: '/09-case-study/openai/06-source-analysis' },
            { text: 'OpenAI 7. Mini Demo', link: '/09-case-study/openai/07-mini-demo' },
            { text: 'OpenAI 8. 企业生产实践', link: '/09-case-study/openai/08-production-practice' },
            { text: 'OpenAI 9. 最佳实践', link: '/09-case-study/openai/09-best-practices' },
            { text: 'Anthropic 总览', link: '/09-case-study/anthropic/' },
            { text: 'Anthropic 1. 背景', link: '/09-case-study/anthropic/01-background' },
            { text: 'Anthropic 2. 核心思想', link: '/09-case-study/anthropic/02-core-ideas' },
            { text: 'Anthropic 3. 架构设计', link: '/09-case-study/anthropic/03-architecture' },
            { text: 'Anthropic 4. 训练与推理', link: '/09-case-study/anthropic/04-training-and-inference' },
            { text: 'Anthropic 5. 核心模块', link: '/09-case-study/anthropic/05-core-modules' },
            { text: 'Anthropic 6. 源码与可解释性', link: '/09-case-study/anthropic/06-source-analysis' },
            { text: 'Anthropic 7. Mini Demo', link: '/09-case-study/anthropic/07-mini-demo' },
            { text: 'Anthropic 8. 企业生产实践', link: '/09-case-study/anthropic/08-production-practice' },
            { text: 'Anthropic 9. 最佳实践', link: '/09-case-study/anthropic/09-best-practices' },
            { text: 'Meta 总览', link: '/09-case-study/meta/' },
            { text: 'Meta 1. 背景', link: '/09-case-study/meta/01-background' },
            { text: 'Meta 2. 核心思想', link: '/09-case-study/meta/02-core-ideas' },
            { text: 'Meta 3. 架构设计', link: '/09-case-study/meta/03-architecture' },
            { text: 'Meta 4. 训练与推理', link: '/09-case-study/meta/04-training-and-inference' },
            { text: 'Meta 5. 核心模块', link: '/09-case-study/meta/05-core-modules' },
            { text: 'Meta 6. 源码与生态分析', link: '/09-case-study/meta/06-source-analysis' },
            { text: 'Meta 7. Mini Demo', link: '/09-case-study/meta/07-mini-demo' },
            { text: 'Meta 8. 企业生产实践', link: '/09-case-study/meta/08-production-practice' },
            { text: 'Meta 9. 最佳实践', link: '/09-case-study/meta/09-best-practices' },
            { text: 'Google 总览', link: '/09-case-study/google/' },
            { text: 'Google 1. 背景', link: '/09-case-study/google/01-background' },
            { text: 'Google 2. 核心思想', link: '/09-case-study/google/02-core-ideas' },
            { text: 'Google 3. 架构设计', link: '/09-case-study/google/03-architecture' },
            { text: 'Google 4. 训练与推理', link: '/09-case-study/google/04-training-and-inference' },
            { text: 'Google 5. 核心模块', link: '/09-case-study/google/05-core-modules' },
            { text: 'Google 6. 源码与生态分析', link: '/09-case-study/google/06-source-analysis' },
            { text: 'Google 7. Mini Demo', link: '/09-case-study/google/07-mini-demo' },
            { text: 'Google 8. 企业生产实践', link: '/09-case-study/google/08-production-practice' },
            { text: 'Google 9. 最佳实践', link: '/09-case-study/google/09-best-practices' },
          ],
        },
      ],

      sidebar,

      editLink: {
        pattern: 'https://github.com/cypggs/AI_Infra_Handbook/edit/main/docs/:path',
        text: '在 GitHub 上编辑此页',
      },

      socialLinks: [
        { icon: 'github', link: 'https://github.com/cypggs/AI_Infra_Handbook' },
      ],

      footer: {
        message: 'Released under CC-BY-SA-4.0 License.',
        copyright: 'Copyright © 2026-present AI Infra Handbook Contributors',
      },

      search: {
        provider: 'local',
      },

      outline: {
        level: [2, 3],
        label: '目录',
      },

      docFooter: {
        prev: '上一篇',
        next: '下一篇',
      },

      lastUpdatedText: '最后更新',
      returnToTopLabel: '回到顶部',
      sidebarMenuLabel: '菜单',
      darkModeSwitchLabel: '主题',
    },

    sitemap: {
      hostname: 'https://ai-infra.cypggs.com',
    },
  })
)
