import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Sidebar = [
  {
    text: '开始',
    items: [
      { text: '首页', link: '/' },
      { text: '阅读指南', link: '/guide' },
    ],
  },
  {
    text: '01. 基础',
    collapsed: false,
    items: [{ text: '概述', link: '/01-foundation/' }],
  },
  {
    text: '02. 云原生',
    collapsed: false,
    items: [{ text: '概述', link: '/02-cloud-native/' }],
  },
  {
    text: '03. AI 平台',
    collapsed: false,
    items: [{ text: '概述', link: '/03-ai-platform/' }],
  },
  {
    text: '04. LLMOps',
    collapsed: false,
    items: [
      { text: '概述', link: '/04-llmops/' },
      {
        text: 'vLLM',
        collapsed: false,
        items: [
          { text: '总览', link: '/04-llmops/vllm/' },
          { text: '1. 背景', link: '/04-llmops/vllm/01-background' },
          { text: '2. 核心思想', link: '/04-llmops/vllm/02-core-ideas' },
          { text: '3. 架构设计', link: '/04-llmops/vllm/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/04-llmops/vllm/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/04-llmops/vllm/05-core-modules' },
          { text: '6. 源码分析', link: '/04-llmops/vllm/06-source-analysis' },
          { text: '7. 工程实践', link: '/04-llmops/vllm/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/04-llmops/vllm/08-production-practice' },
          { text: '9. 最佳实践', link: '/04-llmops/vllm/09-best-practices' },
          { text: '10. 面试题', link: '/04-llmops/vllm/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/04-llmops/vllm/11-further-reading' },
        ],
      },
      {
        text: 'SGLang',
        collapsed: false,
        items: [
          { text: '总览', link: '/04-llmops/sglang/' },
          { text: '1. 背景', link: '/04-llmops/sglang/01-background' },
          { text: '2. 核心思想', link: '/04-llmops/sglang/02-core-ideas' },
          { text: '3. 架构设计', link: '/04-llmops/sglang/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/04-llmops/sglang/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/04-llmops/sglang/05-core-modules' },
          { text: '6. 源码分析', link: '/04-llmops/sglang/06-source-analysis' },
          { text: '7. 工程实践', link: '/04-llmops/sglang/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/04-llmops/sglang/08-production-practice' },
          { text: '9. 最佳实践', link: '/04-llmops/sglang/09-best-practices' },
          { text: '10. 面试题', link: '/04-llmops/sglang/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/04-llmops/sglang/11-further-reading' },
        ],
      },
      {
        text: 'TensorRT-LLM',
        collapsed: false,
        items: [
          { text: '总览', link: '/04-llmops/tensorrt-llm/' },
          { text: '1. 背景', link: '/04-llmops/tensorrt-llm/01-background' },
          { text: '2. 核心思想', link: '/04-llmops/tensorrt-llm/02-core-ideas' },
          { text: '3. 架构设计', link: '/04-llmops/tensorrt-llm/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/04-llmops/tensorrt-llm/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/04-llmops/tensorrt-llm/05-core-modules' },
          { text: '6. 源码分析', link: '/04-llmops/tensorrt-llm/06-source-analysis' },
          { text: '7. 工程实践', link: '/04-llmops/tensorrt-llm/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/04-llmops/tensorrt-llm/08-production-practice' },
          { text: '9. 最佳实践', link: '/04-llmops/tensorrt-llm/09-best-practices' },
          { text: '10. 面试题', link: '/04-llmops/tensorrt-llm/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/04-llmops/tensorrt-llm/11-further-reading' },
        ],
      },
      {
        text: 'Triton Inference Server',
        collapsed: false,
        items: [
          { text: '总览', link: '/04-llmops/triton/' },
          { text: '1. 背景', link: '/04-llmops/triton/01-background' },
          { text: '2. 核心思想', link: '/04-llmops/triton/02-core-ideas' },
          { text: '3. 架构设计', link: '/04-llmops/triton/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/04-llmops/triton/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/04-llmops/triton/05-core-modules' },
          { text: '6. 源码分析', link: '/04-llmops/triton/06-source-analysis' },
          { text: '7. 工程实践', link: '/04-llmops/triton/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/04-llmops/triton/08-production-practice' },
          { text: '9. 最佳实践', link: '/04-llmops/triton/09-best-practices' },
          { text: '10. 面试题', link: '/04-llmops/triton/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/04-llmops/triton/11-further-reading' },
        ],
      },
      {
        text: 'LLM Gateway',
        collapsed: false,
        items: [
          { text: '总览', link: '/04-llmops/llm-gateway/' },
          { text: '1. 背景', link: '/04-llmops/llm-gateway/01-background' },
          { text: '2. 核心思想', link: '/04-llmops/llm-gateway/02-core-ideas' },
          { text: '3. 架构设计', link: '/04-llmops/llm-gateway/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/04-llmops/llm-gateway/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/04-llmops/llm-gateway/05-core-modules' },
          { text: '6. 源码分析', link: '/04-llmops/llm-gateway/06-source-analysis' },
          { text: '7. 工程实践', link: '/04-llmops/llm-gateway/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/04-llmops/llm-gateway/08-production-practice' },
          { text: '9. 最佳实践', link: '/04-llmops/llm-gateway/09-best-practices' },
          { text: '10. 面试题', link: '/04-llmops/llm-gateway/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/04-llmops/llm-gateway/11-further-reading' },
        ],
      },
    ],
  },
  {
    text: '05. Agent',
    collapsed: false,
    items: [
      { text: '概述', link: '/05-agent/' },
      {
        text: 'Agent Runtime',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/agent-runtime/' },
          { text: '1. 背景', link: '/05-agent/agent-runtime/01-background' },
          { text: '2. 核心思想', link: '/05-agent/agent-runtime/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/agent-runtime/03-architecture' },
          { text: '4. Runtime 工作流程', link: '/05-agent/agent-runtime/04-runtime-workflow' },
          { text: '5. 核心模块', link: '/05-agent/agent-runtime/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/agent-runtime/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/agent-runtime/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/agent-runtime/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/agent-runtime/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/agent-runtime/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/agent-runtime/11-further-reading' },
        ],
      },
      {
        text: 'Memory',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/memory/' },
          { text: '1. 背景', link: '/05-agent/memory/01-background' },
          { text: '2. 核心思想', link: '/05-agent/memory/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/memory/03-architecture' },
          { text: '4. 记忆生命周期', link: '/05-agent/memory/04-memory-lifecycle' },
          { text: '5. 核心模块', link: '/05-agent/memory/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/memory/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/memory/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/memory/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/memory/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/memory/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/memory/11-further-reading' },
        ],
      },
      {
        text: 'Multi-Agent',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/multi-agent/' },
          { text: '1. 背景', link: '/05-agent/multi-agent/01-background' },
          { text: '2. 核心思想', link: '/05-agent/multi-agent/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/multi-agent/03-architecture' },
          { text: '4. 协作模式', link: '/05-agent/multi-agent/04-collaboration-patterns' },
          { text: '5. 核心模块', link: '/05-agent/multi-agent/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/multi-agent/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/multi-agent/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/multi-agent/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/multi-agent/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/multi-agent/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/multi-agent/11-further-reading' },
        ],
      },
      {
        text: 'Reflection',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/reflection/' },
          { text: '1. 背景', link: '/05-agent/reflection/01-background' },
          { text: '2. 核心思想', link: '/05-agent/reflection/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/reflection/03-architecture' },
          { text: '4. 反思循环', link: '/05-agent/reflection/04-reflection-loop' },
          { text: '5. 核心模块', link: '/05-agent/reflection/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/reflection/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/reflection/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/reflection/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/reflection/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/reflection/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/reflection/11-further-reading' },
        ],
      },
      {
        text: 'MCP',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/mcp/' },
          { text: '1. 背景', link: '/05-agent/mcp/01-background' },
          { text: '2. 核心思想', link: '/05-agent/mcp/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/mcp/03-architecture' },
          { text: '4. 协议工作流程', link: '/05-agent/mcp/04-protocol-workflow' },
          { text: '5. 核心模块', link: '/05-agent/mcp/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/mcp/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/mcp/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/mcp/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/mcp/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/mcp/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/mcp/11-further-reading' },
        ],
      },
      {
        text: 'Planning',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/planning/' },
          { text: '1. 背景', link: '/05-agent/planning/01-background' },
          { text: '2. 核心思想', link: '/05-agent/planning/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/planning/03-architecture' },
          { text: '4. 规划循环', link: '/05-agent/planning/04-planning-loop' },
          { text: '5. 核心模块', link: '/05-agent/planning/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/planning/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/planning/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/planning/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/planning/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/planning/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/planning/11-further-reading' },
        ],
      },
      {
        text: 'Tool Use',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/tool-use/' },
          { text: '1. 背景', link: '/05-agent/tool-use/01-background' },
          { text: '2. 核心思想', link: '/05-agent/tool-use/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/tool-use/03-architecture' },
          { text: '4. Tool-Use 工作流程', link: '/05-agent/tool-use/04-tool-use-workflow' },
          { text: '5. 核心模块', link: '/05-agent/tool-use/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/tool-use/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/tool-use/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/tool-use/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/tool-use/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/tool-use/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/tool-use/11-further-reading' },
        ],
      },
      {
        text: 'Agent OS',
        collapsed: false,
        items: [
          { text: '总览', link: '/05-agent/agent-os/' },
          { text: '1. 背景', link: '/05-agent/agent-os/01-background' },
          { text: '2. 核心思想', link: '/05-agent/agent-os/02-core-ideas' },
          { text: '3. 架构设计', link: '/05-agent/agent-os/03-architecture' },
          { text: '4. Agent OS 工作流程', link: '/05-agent/agent-os/04-agent-os-workflow' },
          { text: '5. 核心模块', link: '/05-agent/agent-os/05-core-modules' },
          { text: '6. 源码分析', link: '/05-agent/agent-os/06-source-analysis' },
          { text: '7. 工程实践', link: '/05-agent/agent-os/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/05-agent/agent-os/08-production-practice' },
          { text: '9. 最佳实践', link: '/05-agent/agent-os/09-best-practices' },
          { text: '10. 面试题', link: '/05-agent/agent-os/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/05-agent/agent-os/11-further-reading' },
        ],
      },
    ],
  },
  {
    text: '06. RAG',
    collapsed: false,
    items: [
      { text: '概述', link: '/06-rag/' },
      { text: '1. 背景', link: '/06-rag/01-background' },
      { text: '2. 核心概念', link: '/06-rag/02-core-ideas' },
      { text: '3. 架构设计', link: '/06-rag/03-architecture' },
      { text: '4. RAG 流水线', link: '/06-rag/04-rag-pipeline' },
      { text: '5. 核心模块', link: '/06-rag/05-core-modules' },
      { text: '6. 源码与生态分析', link: '/06-rag/06-source-analysis' },
      { text: '7. Mini Demo', link: '/06-rag/07-mini-demo' },
      { text: '8. 企业生产实践', link: '/06-rag/08-production-practice' },
      { text: '9. 最佳实践', link: '/06-rag/09-best-practices' },
      { text: '10. 面试题', link: '/06-rag/10-interview-questions' },
      { text: '11. 延伸阅读', link: '/06-rag/11-further-reading' },
    ],
  },
  {
    text: '07. AI SRE',
    collapsed: false,
    items: [
      { text: '概述', link: '/07-ai-sre/' },
      { text: '1. 背景', link: '/07-ai-sre/01-background' },
      { text: '2. 核心概念', link: '/07-ai-sre/02-core-ideas' },
      { text: '3. 架构设计', link: '/07-ai-sre/03-architecture' },
      { text: '4. AI SRE 工作流程', link: '/07-ai-sre/04-ai-sre-workflow' },
      { text: '5. 核心模块', link: '/07-ai-sre/05-core-modules' },
      { text: '6. 源码与生态分析', link: '/07-ai-sre/06-source-analysis' },
      { text: '7. Mini Demo', link: '/07-ai-sre/07-mini-demo' },
      { text: '8. 企业生产实践', link: '/07-ai-sre/08-production-practice' },
      { text: '9. 最佳实践', link: '/07-ai-sre/09-best-practices' },
      { text: '10. 面试题', link: '/07-ai-sre/10-interview-questions' },
      { text: '11. 延伸阅读', link: '/07-ai-sre/11-further-reading' },
    ],
  },
  {
    text: '08. 安全',
    collapsed: false,
    items: [
      { text: '概述', link: '/08-security/' },
      { text: '1. 背景', link: '/08-security/01-background' },
      { text: '2. 核心思想', link: '/08-security/02-core-ideas' },
      { text: '3. 架构设计', link: '/08-security/03-architecture' },
      { text: '4. AI 安全生命周期', link: '/08-security/04-security-lifecycle' },
      { text: '5. 核心模块', link: '/08-security/05-core-modules' },
      { text: '6. 源码与生态分析', link: '/08-security/06-source-analysis' },
      { text: '7. Mini Demo', link: '/08-security/07-mini-demo' },
      { text: '8. 企业生产实践', link: '/08-security/08-production-practice' },
      { text: '9. 最佳实践', link: '/08-security/09-best-practices' },
      { text: '10. 面试题', link: '/08-security/10-interview-questions' },
      { text: '11. 延伸阅读', link: '/08-security/11-further-reading' },
    ],
  },
  {
    text: '09. 案例研究',
    collapsed: false,
    items: [
      { text: '概述', link: '/09-case-study/' },
      {
        text: 'OpenAI',
        collapsed: false,
        items: [
          { text: '总览', link: '/09-case-study/openai/' },
          { text: '1. 背景', link: '/09-case-study/openai/01-background' },
          { text: '2. 核心思想', link: '/09-case-study/openai/02-core-ideas' },
          { text: '3. 架构设计', link: '/09-case-study/openai/03-architecture' },
          { text: '4. 训练与推理', link: '/09-case-study/openai/04-training-and-inference' },
          { text: '5. 核心模块', link: '/09-case-study/openai/05-core-modules' },
          { text: '6. 源码与生态分析', link: '/09-case-study/openai/06-source-analysis' },
          { text: '7. Mini Demo', link: '/09-case-study/openai/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/09-case-study/openai/08-production-practice' },
          { text: '9. 最佳实践', link: '/09-case-study/openai/09-best-practices' },
          { text: '10. 面试题', link: '/09-case-study/openai/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/09-case-study/openai/11-further-reading' },
        ],
      },
      {
        text: 'Anthropic',
        collapsed: false,
        items: [
          { text: '总览', link: '/09-case-study/anthropic/' },
          { text: '1. 背景', link: '/09-case-study/anthropic/01-background' },
          { text: '2. 核心思想', link: '/09-case-study/anthropic/02-core-ideas' },
          { text: '3. 架构设计', link: '/09-case-study/anthropic/03-architecture' },
          { text: '4. 训练与推理', link: '/09-case-study/anthropic/04-training-and-inference' },
          { text: '5. 核心模块', link: '/09-case-study/anthropic/05-core-modules' },
          { text: '6. 源码与可解释性', link: '/09-case-study/anthropic/06-source-analysis' },
          { text: '7. Mini Demo', link: '/09-case-study/anthropic/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/09-case-study/anthropic/08-production-practice' },
          { text: '9. 最佳实践', link: '/09-case-study/anthropic/09-best-practices' },
          { text: '10. 面试题', link: '/09-case-study/anthropic/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/09-case-study/anthropic/11-further-reading' },
        ],
      },
      {
        text: 'Meta',
        collapsed: false,
        items: [
          { text: '总览', link: '/09-case-study/meta/' },
          { text: '1. 背景', link: '/09-case-study/meta/01-background' },
          { text: '2. 核心思想', link: '/09-case-study/meta/02-core-ideas' },
          { text: '3. 架构设计', link: '/09-case-study/meta/03-architecture' },
          { text: '4. 训练与推理', link: '/09-case-study/meta/04-training-and-inference' },
          { text: '5. 核心模块', link: '/09-case-study/meta/05-core-modules' },
          { text: '6. 源码与生态分析', link: '/09-case-study/meta/06-source-analysis' },
          { text: '7. Mini Demo', link: '/09-case-study/meta/07-mini-demo' },
          { text: '8. 企业生产实践', link: '/09-case-study/meta/08-production-practice' },
          { text: '9. 最佳实践', link: '/09-case-study/meta/09-best-practices' },
          { text: '10. 面试题', link: '/09-case-study/meta/10-interview-questions' },
          { text: '11. 延伸阅读', link: '/09-case-study/meta/11-further-reading' },
        ],
      },
    ],
  },
  {
    text: '10. 路线与资源',
    collapsed: false,
    items: [
      { text: '概述', link: '/10-roadmap/' },
      { text: '学习路线', link: '/10-roadmap/learning-path' },
      { text: '面试指南', link: '/10-roadmap/interview-guide' },
    ],
  },
]
